### ISSUE TITLE
Not getting controller events in onKey and in dispatchKeyEvent method

### ISSUE THREAD

**Issue by chnouman** [wearvr/pico-vr-unity-sdk-instructions#2]
I'm developing app for Pico VR and want to put input through Pico VR controller. I'm only getting event of controller's home button. How can I get the events for other buttons?

**Comment by WEARVR-Jon** [comment]
You should be able to use the input methods explained on the controller section of the documentation found: https://github.com/wearvr/pico-vr-unity-sdk-instructions/blob/master/docs/pico-goblin-and-neo-controllers.md#hummingbird-controller

If you are using a G2 then the controller responds in the same way as the Neo controller.

**Comment by chnouman** [comment]
@WEARVR-Jon you are right but I'm not using it with unity. I'm inside the android studio and installing the app as a launcher App to the pico VR. Everything is working perfectly but I'm unable to get key events other than home button event.

**Comment by WEARVR-Jon** [comment]
@chnouman Pico only currently supports Unity and Unreal with their SDKs. I'll let you know if I'm able to find out any more on this.

**Comment by chnouman** [comment]
@WEARVR-Jon sure, please and thank you for the quick response.

 Yes, I know Pico only supports Unity and Unreal but we are working out of the box and trying to get inputs from the controller.

**Comment by WEARVR-Jon** [comment]
No worries, I'll let you know what I find out.

Cheers,
Jon


*Jon Byles*
*Developer Liaison Manager*

Skype: jon@wearvr.com
Website: www.wearvr.com




ᐧ

**Comment by WEARVR-Jon** [comment]
Hi @chnouman 

Please find the Jar file here: https://drive.google.com/open?id=1A37RmLB2fF2nFBtNMcIkxf4dLijYxv8k

I have heard back directly from Pico tech regarding this and they have said:

"Our SDK integrated a jar file that included an interface for KeyEvent. 

There are two interfaces in this jar file to get key events: 
1. 
Description: This function can return a string value of key events of controller. Returned content is written in form of JsonArray.
Package Name: com.picovr.picovrlib.hummingbirdclient
Class Name: HbClientActivity
Function Definition: public static String getHBKeyEvent();
Return Type: String
Return Value: This function return a JsonArray defined as following: 
key_value[0] = mKeyEvent.touchpadX;

           key_value[1] = mKeyEvent.touchpadY;

           key_value[2] = mKeyEvent.homeKeyPress;

           key_value[3] = mKeyEvent.appKeyPress;

           key_value[4] = mKeyEvent.clickKeyPress;

           key_value[5] = mKeyEvent.volumeUpKeyPress;

           key_value[6] = mKeyEvent.volumeDownKeyPress;

       key_value[7] = mKeyEvent.batteryLevel;


2. 
Description: This function is used to get Trigger Button event.
Package Name: com.picovr.picovrlib.hummingbirdclient
Class Name: HbClientActivity
Function Definition: public static int getTriggerKeyEvent()
Return Type: Int"

I hope this helps and let me know if there is any other issues that you're facing. 

Best,
Jon

**Comment by chnouman** [comment]
@WEARVR-Jon Hi buddy really thank you for this. I'll test this by tomorrow and let you know. :blush:

**Comment by WEARVR-Jon** [comment]
No worries,

Good luck,
Jon


*Jon Byles*
*Developer Liaison Manager*

Skype: jon@wearvr.com
Website: www.wearvr.com




ᐧ
